Repository insightsengineering/teal.transform, pull requests merged in 2024-02, with the labels that each got.

#177 Removes `return` call if it is the last expression
  R/choices_labeled.R
  R/choices_selected.R
  R/filter_spec.R
  R/get_dplyr_call.R
  R/get_merge_call.R
  R/include_css_js.R
  R/merge_datasets.R
  R/resolve.R
  R/select_spec.R
  R/utils.R
  man/choices_selected.Rd
  man/value_choices.Rd
  man/variable_choices.Rd
Labels: core

#186 Replace `is.atomic` calls with checkmate equivalents
  DESCRIPTION
  R/choices_selected.R
  R/resolve.R
  R/select_spec.R
  R/utils.R
Labels: core, bug

#183 Fixing vignettes
  vignettes/data-extract-merge.Rmd
  vignettes/data-extract.Rmd
  vignettes/data-merge.Rmd
  vignettes/teal-transform.Rmd
Labels: core

#178 Convert "# nolint" to specific rule exception
  .lintr
  R/Queue.R
  R/choices_labeled.R
  R/choices_selected.R
  R/data_extract_module.R
  R/filter_spec.R
  R/get_dplyr_call.R
  R/get_merge_call.R
  R/select_spec.R
  R/zzz.R
  data-raw/data.R
  tests/testthat/test-data_extract_module.R
  tests/testthat/test-data_extract_multiple_srv.R
  tests/testthat/test-data_extract_spec.R
  tests/testthat/test-data_extract_srv.R
  tests/testthat/test-delayed_data_extract.R
  tests/testthat/test-dplyr_call_examples.R
  tests/testthat/test-filter_spec.R
  tests/testthat/test-merge_utils.R
  tests/testthat/test-resolve.R
  tests/testthat/test-resolve_delayed.R
  tests/testthat/test-select_spec.R
  tests/testthat/test-value_choices.R
  tests/testthat/test-variable_choices.R
  vignettes/data-extract-merge.Rmd
  vignettes/data-extract.Rmd
  vignettes/data-merge.Rmd
Labels: core

#197 minor changes.
  R/all_choices.R
  R/call_utils.R
  R/choices_labeled.R
  R/choices_selected.R
  R/data.R
  R/data_extract_datanames.R
  R/data_extract_module.R
  R/data_extract_spec.R
  R/filter_spec.R
  R/get_dplyr_call.R
  R/get_merge_call.R
  R/include_css_js.R
  R/input_checks.R
  R/merge_datasets.R
  R/merge_expression_module.R
  man/all_choices.Rd
  man/call_check_parse_varname.Rd
  man/call_condition_choice.Rd
  man/check_no_multiple_selection.Rd
  man/choices_labeled.Rd
  man/choices_selected.Rd
  man/data_extract_multiple_srv.Rd
  man/data_extract_spec.Rd
  man/datanames_input.Rd
  man/filter_spec.Rd
  man/get_dplyr_call_data.Rd
  man/get_extract_datanames.Rd
  man/get_merge_call.Rd
  man/include_css_files.Rd
  man/is_single_dataset.Rd
  man/merge_expression_module.Rd
  man/rADTTE.Rd
  man/value_choices.Rd
  man/variable_choices.Rd
Labels: core

#198 removing internal functions' examples
  R/call_utils.R
  R/data_extract_filter_module.R
  R/data_extract_module.R
  R/data_extract_select_module.R
  R/data_extract_single_module.R
  R/filter_spec.R
  R/get_dplyr_call.R
  R/get_merge_call.R
  R/merge_datasets.R
  R/resolve.R
  man/call_condition_choice.Rd
  man/call_condition_logical.Rd
  man/call_condition_range.Rd
  man/call_condition_range_date.Rd
  man/call_condition_range_posixct.Rd
  man/call_extract_array.Rd
  man/call_extract_list.Rd
  man/call_extract_matrix.Rd
  man/call_with_colon.Rd
  man/calls_combine_by.Rd
  man/cond_data_extract_single_ui.Rd
  man/data_extract_filter_ui.Rd
  man/data_extract_select_ui.Rd
  man/data_extract_single_ui.Rd
  man/filter_spec_internal.Rd
  man/get_dplyr_call.Rd
  man/get_filter_call.Rd
  man/get_initial_filter_values.Rd
  man/get_merge_key_i.Rd
  man/get_rename_call.Rd
  man/get_reshape_call.Rd
  man/get_select_call.Rd
  man/merge_selectors.Rd
  man/resolve.Rd
Labels: core

#188 Removes magrittr from Depends
  .pre-commit-config.yaml
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/teal.transform-package.R
  man/reexports.Rd
Labels: core

#199 [Docs] Refine the vignettes
  inst/design/basic_concept.drawio
  vignettes/data-extract-merge.Rmd
  vignettes/data-extract.Rmd
  vignettes/data-merge.Rmd
  vignettes/images/app-data-extract-merge.png
  vignettes/images/app-data-extract.png
  vignettes/images/app-data-merge-1.png
  vignettes/images/app-data-merge-2.png
  vignettes/images/basic_concept.svg
  vignettes/images/data_extract_spec/basic_concept.png
  vignettes/teal-transform.Rmd
Labels: core, documentation
